# -*- coding: utf-8 -*-
"""File_Handling.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1PJVOrGM0ZIg09eVfSB6p3XoVI079qEJT

# File_handling
"""

import os

"""# knowing current working directory

"""

# knowing
os.getcwd()

# knowing files avilable in side directory
os.listdir()

"""# modes in file handling

In Python, the open function supports several file modes that determine how the file will be opened. Here are the most commonly used modes:

'r': Read mode - Opens a file for reading. If the file does not exist, it raises a FileNotFoundError.

'w': Write mode - Opens a file for writing. If the file already exists, it truncates the file. If the file does not exist, it creates a new file.

'a': Append mode - Opens a file for appending. If the file does not exist, it creates a new file. Data is added to the end of the file without truncating it.

'x': Exclusive creation mode - Creates a new file and opens it for writing. If the file already exists, the operation fails.

'b': Binary mode - Opens a file in binary mode. This mode is used for non-text files like images or executable files. It is used in conjunction with other modes (e.g., 'rb', 'wb', 'ab').

't': Text mode - Opens a file in text mode. This is the default mode if none is specified. It can also be used in conjunction with other modes (e.g., 'rt', 'wt', 'at').

'+': Update mode - Opens a file for updating (both reading and writing). It is used in conjunction with other modes (e.g., 'r+', 'w+', 'a+').

# creating a text file
"""

# creating text file file we use x
f=open('practice.txt','x')
f.close()
# creating with other example
with open('practicee.txt','x') as file_txt:
  file_txt.close()

"""# writing into text file"""

# writing  text file other example
with open('practice1.txt','w') as f:
  f.write('this is practice1 text file')
  f.close()

"""# reading into a text file"""

# reading content from text file
f=open('practice.txt','r')
print(f.read())
f.close()

"""# reading line by line"""

#readling line by line
f=open('practice3.txt','r')

print(f.readline())
print(f.readline())
print(f.readline())
f.close()

"""# readlines"""

# reaadlines exampple
f=open('practice3.txt','r')

print(f.readlines())

f.close()

"""# appening into a file


"""

# append in this already exitsting file avilable writing on that
f=open('practice3.txt','a')
f.write('im fine')
f.close()

"""# read binary file"""

# read binary
f=open('practice.bin','rb')
print(f.read())
f.close()

"""# write binary


"""

f=open('practice.txt','wb')
binary_data = os.urandom(1024)
f.write(binary_data)
f.close()

""" # read and write mode file

"""

# Read and write mode
with open("practice3.txt", "r+") as file:
    content = file.read()
    file.write("\nUpdating the file.")
    f.close()